version: '3'

services:
  zoo1:
    image: btardio/zk #zookeeper
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181" # 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - zoo-volume-data-01:/data/
      - zoo-volume-datalog-01:/datalog/
    networks:
      - zksolr-network

  zoo2:
    image: btardio/zk #zookeeper
    restart: always
    hostname: zoo2
    ports:
      - "2182:2181" #2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - zoo-volume-data-02:/data/
      - zoo-volume-datalog-02:/datalog/
    networks:
      - zksolr-network

  zoo3:
    image: btardio/zk # zookeeper
    restart: always
    hostname: zoo3
    ports:
      - "2183:2181" #2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    volumes:
      - zoo-volume-data-03:/data/
      - zoo-volume-datalog-03:/datalog/
    networks:
      - zksolr-network


  solr00:
    image: solr # btardio/solr #solr
    ports:
      - "8983:8983"
    command: docker-entrypoint.sh solr config -action set-property -property solr.data.dir -value "/solr_data/" -c encorea -zkHost zoo1:2181
    command: docker-entrypoint.sh solr start -f -c -p 8983 -z zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - solr-cores:/solr_data/
    networks:
      - zksolr-network
    depends_on:
      - "zoo1"
      - "zoo3"
      - "zoo2"

  #solr01:
    #image: solr #btardio/solr
    #ports:
      #- "8984:8983"
    #command: docker-entrypoint.sh solr config -action set-property -property solr.data.dir -value "/solr_data/" -c encorea -zkHost zoo1:2181
    #command: docker-entrypoint.sh solr start -f -c -p 8983 -z zoo1:2181,zoo2:2181,zoo3:2181
    #volumes:
      #- solr-cores:/solr_data/
    #networks:
      #- zksolr-network
    #depends_on:
      #- "zoo1"
      #- "zoo3"
      #- "zoo2"


  #solr02:
    #image: solr #btardio/solr
    #ports:
      #- "8985:8983"
    #command: docker-entrypoint.sh solr config -action set-property -property solr.data.dir -value "/solr_data/" -c encorea -zkHost zoo1:2181
    #command: docker-entrypoint.sh solr start -f -c -p 8983 -z zoo1:2181,zoo2:2181,zoo3:2181
    #volumes:
      #- solr-cores:/solr_data/
    #networks:
      #- zksolr-network
    #depends_on:
      #- "zoo1"
      #- "zoo3"
      #- "zoo2"
        
        
  #solr03:
    #image: solr #btardio/solr
    #ports:
      #- "8986:8983"
    #command: docker-entrypoint.sh solr config -action set-property -property solr.data.dir -value "/solr_data/" -c encorea -zkHost zoo1:2181
    #command: docker-entrypoint.sh solr start -f -c -p 8983 -z zoo1:2181,zoo2:2181,zoo3:2181
    #volumes:
      #- solr-cores:/solr_data/
    #networks:
      #- zksolr-network
    #depends_on:
      #- "zoo1"
      #- "zoo3"
      #- "zoo2"


  #solr04:
    #image: solr #btardio/solr
    #ports:
      #- "8987:8983"
    #command: docker-entrypoint.sh solr config -action set-property -property solr.data.dir -value "/solr_data/" -c encorea -zkHost zoo1:2181
    #command: docker-entrypoint.sh solr start -f -c -p 8983 -z zoo1:2181,zoo2:2181,zoo3:2181
    #volumes:
      #- solr-cores:/solr_data/
    #networks:
      #- zksolr-network
    #depends_on:
      #- "zoo1"
      #- "zoo3"
      #- "zoo2"


  #solr05:
    #image: solr #btardio/solr
    #ports:
      #- "8988:8983"
    #command: docker-entrypoint.sh solr config -action set-property -property solr.data.dir -value "/solr_data/" -c encorea -zkHost zoo1:2181
    #command: docker-entrypoint.sh solr start -f -c -p 8983 -z zoo1:2181,zoo2:2181,zoo3:2181
    #volumes:
      #- solr-cores:/solr_data/
    #networks:
      #- zksolr-network
    #depends_on:
      #- "zoo1"
      #- "zoo3"
      #- "zoo2"

        
networks:
  zksolr-network:
#    driver: overlay # remove comment for deployment


volumes:
  solr-cores:
  zoo-volume-data-01:
  zoo-volume-datalog-01:
  zoo-volume-data-02:
  zoo-volume-datalog-02:
  zoo-volume-data-03:
  zoo-volume-datalog-03:
